apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowedTags
metadata:
  name: container-image-must-not-have-latest-tag-exception
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
        - key: company/exception-present
          operator: NotIn
          values: [granted]
    labelSelector:
      matchExpressions:
        - key: default-ns/disallowed-tags-exception
          operator: NotIn
          values: [granted]
#    namespaceSelector:
#      matchExpressions:
#        # testing exception here
#        - key: "company/exception-present"
#          operator: "DoesNotExist"
#          #operator: "NotIn"
#          #values:
#          #  - "true"
#    labelSelector:
#      matchExpressions:
#        # testing exception here
#        - key: "default-ns/disallowed-tags-exception"
#          operator: "NotIn"
#          values:
#            - "granted"
  parameters:
    tags: ["latest"]
